version: '3'
services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sport
    ports:
      - '5433:5432'

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env

networks:
  postgres:
    driver: bridge
