version: "3"
services:
  postgres:
    image: postgis/postgis:13-3.1
    networks:
      - postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create_database.sql
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"

networks:
  postgres:
    driver: bridge
